WITH CTE AS (SELECT MONTH(ORDER_DATE) AS Order_Month,
sum(QUANTITY) AS TOTAL_QUANTITY,
sum(TOTAL_AMOUNT) AS TOTAL_AMOUNT,
CUSTOMER_AGE_GROUP FROM SALES
GROUP BY ORDER_MONTH, CUSTOMER_AGE_GROUP
order by Order_Month asc)

,CTE2 AS (SELECT ORDER_MONTH,
TOTAL_QUANTITY,
TOTAL_AMOUNT,
CUSTOMER_AGE_GROUP,
RANK() OVER(PARTITION BY ORDER_MONTH ORDER BY TOTAL_AMOUNT DESC) AS Revenue_RANK 
FROM CTE)

SELECT 
    Order_Month,
    CUSTOMER_AGE_GROUP AS Top_Age_Group,
    Total_amount,
    Total_Quantity,
    revenue_rank
FROM CTE2
where revenue_rank = 1
ORDER BY order_month asc;





